# Version -> Cek versi berdasarkan versi docker engine
version: '3.1'

# Setup
services: #
    
    # PHP
    php:
        #image: php:8.0-apache -> untuk menentukan versi image yang akan dipakai
        build: 
            context: ./development
            dockerfile: Dockerfile
        depends_on:
            - db
        restart: always
        ports:
            - "5000:80"
        volumes:
            - ./development:/var/www/html

    # PHPMyAdmin
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - "5050:80"
        environment:
            PMA_HOST: db

    # MySQL
    db:
        image: mysql:latest
        restart: always
        volumes:
            - review_cust_db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: review_cust
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "5080:3306"
#Volumes
volumes:
    review_cust_db:
    review_cust_uploads: